### ISSUE TITLE
patch missing

### ISSUE THREAD

**Issue by jBitHub** [wiltondb/actions_test#1]
The file patch.exe is missing from the asset diffutils-3.6.zip.

**Comment by staticlibs** [comment]
Hi, this is correct, [diffutils](https://savannah.gnu.org/projects/diffutils/) project contain `diff`, `diff3`, `sdiff` and `cmp` utilities. `patch` utility has [its own project](https://savannah.gnu.org/projects/patch/). There are no plans to add it here.

**Comment by jBitHub** [comment]
Thank you very much for the quick answer.
On the patch project page you can only download source code. I have not found anything compiled. The page is quite chaotic. The latest news are from 2012.
Is there a way to get a compiled Windows version of patch?
Thanks for your effort.

I copied the patch.exe from the git project as a stopgap.

**Comment by staticlibs** [comment]
[MSYS2](https://www.msys2.org/) will contain the `patch.exe` for sure, but it is likely to depend on a number of shared MSYS2 libs. I never seen a standalone `patch.exe` though, there is some version of it in [GnuWin32](https://gnuwin32.sourceforge.net/packages/patch.htm), but it is very old.

**Comment by jBitHub** [comment]
If it's so hard to find a patch.exe, why are there no plans to include it in the project? Without the patch.exe, you can't do much with the rest of the files.
In the GnuWin32 project there is no patch.exe for download. Only source code. The stopgap solution from the git project has version 2.7.6 from 2012.
MSYS2 looks very complex & interesting. I will have a look at it later.

**Comment by staticlibs** [comment]
> why are there no plans to include it in the project

Unlike diffutils, I myself never needed `patch.exe` as a standalone. Just used one shipped with Cygwin or MSYS (or used `git apply` instead).

> In the GnuWin32 project there is no patch.exe for download

There is one in `patch-2.5.9-7-bin.zip` download there, though I never used it myself.

**Comment by staticlibs** [comment]
Closing as `wontfix`.
